inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Style/FrozenStringLiteralComment:
    Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal

AllCops:
  TargetRubyVersion: 2.5
